export const seedResources = [
  {
    type: "tool" as const,
    name: "ChatGPT",
    slug: "chatgpt",
    tagline: "AI assistant for writing, analysis, coding, and research.",
    description:
      "An AI assistant for conversation, writing, coding, analysis, research, and everyday productivity.",
    websiteUrl: "https://chatgpt.com",
    pricingModel: "freemium" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "tool" as const,
    name: "Claude",
    slug: "claude",
    tagline: "AI assistant for reasoning, writing, coding, and analysis.",
    description:
      "An AI assistant designed for writing, reasoning, coding, research, and working with complex information.",
    websiteUrl: "https://claude.ai",
    pricingModel: "freemium" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "tool" as const,
    name: "Gemini",
    slug: "gemini",
    tagline: "Google's AI assistant for multimodal tasks and productivity.",
    description:
      "A multimodal AI assistant for conversation, research, writing, coding, image understanding, and productivity.",
    websiteUrl: "https://gemini.google.com",
    pricingModel: "freemium" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "tool" as const,
    name: "Perplexity",
    slug: "perplexity",
    tagline: "AI-powered search and research assistant.",
    description:
      "An AI search and research platform that combines conversational answers with web-based information discovery.",
    websiteUrl: "https://www.perplexity.ai",
    pricingModel: "freemium" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "tool" as const,
    name: "Midjourney",
    slug: "midjourney",
    tagline: "Generative AI platform for creating images.",
    description:
      "A generative AI platform focused on creating and exploring images from natural-language instructions.",
    websiteUrl: "https://www.midjourney.com",
    pricingModel: "paid" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "tool" as const,
    name: "Suno",
    slug: "suno",
    tagline: "AI music creation platform.",
    description:
      "An AI music generation platform for creating songs and musical compositions from natural-language ideas.",
    websiteUrl: "https://suno.com",
    pricingModel: "freemium" as const,
    sourceModel: "proprietary" as const,
    isVerified: true,
  },
  {
    type: "framework" as const,
    name: "Ollama",
    slug: "ollama",
    tagline: "Run large language models locally.",
    description:
      "A platform for running and managing large language models locally on personal computers and servers.",
    websiteUrl: "https://ollama.com",
    repositoryUrl: "https://github.com/ollama/ollama",
    pricingModel: "free" as const,
    sourceModel: "open_source" as const,
    isVerified: true,
  },
  {
    type: "framework" as const,
    name: "LangChain",
    slug: "langchain",
    tagline: "Framework for building applications powered by language models.",
    description:
      "An open-source framework and ecosystem for developing applications that use language models, agents, retrieval, and tools.",
    websiteUrl: "https://www.langchain.com",
    repositoryUrl: "https://github.com/langchain-ai/langchain",
    pricingModel: "open_source" as const,
    sourceModel: "open_source" as const,
    isVerified: true,
  },
  {
    type: "model" as const,
    name: "Llama",
    slug: "llama",
    tagline: "Meta's family of large language models.",
    description:
      "A family of large language models from Meta designed for research, development, and a broad range of AI applications.",
    websiteUrl: "https://www.llama.com",
    pricingModel: "free" as const,
    sourceModel: "open_weight" as const,
    isVerified: true,
  },
  {
    type: "model" as const,
    name: "Mistral",
    slug: "mistral",
    tagline: "Open and commercial generative AI models.",
    description:
      "A family of generative AI models and services from Mistral AI, including models available for development and deployment.",
    websiteUrl: "https://mistral.ai",
    pricingModel: "freemium" as const,
    sourceModel: "open_weight" as const,
    isVerified: true,
  },
] as const;
